# Generated by Django 5.0 on 2023-12-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference_room',
            old_name='projector_availability',
            new_name='projector',
        ),
    ]
