# Generated by Django 5.0 on 2023-12-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_rename_projector_availability_conference_room_projector'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conference_Room',
            new_name='ConferenceRoom',
        ),
    ]
